feat(waiter/cilium): Add new gateway
bacchus-snu/cd-manifests pull request #321
Opened 2024-07-13 12:17 UTC by paul2126

2024-07-13 15:05 UTC, nevivurn commented on argocd/waiter/cilium/resources.yaml
> +          - name: web-gateway-certs
이대로 설정하면 gateway에서 사용하는 인증서에 `*.internal` 가 추가가 되는데 인증서는 분리하면 좋을 것 같습니다. 
이름만 다르게 설정하면 cert-manager 등이 Certificate 등 리소스는 생성해줄겁니다

2024-07-13 17:46 UTC, paul2126 commented on argocd/waiter/cilium/resources.yaml
> +          - name: web-gateway-certs
넵 반영했습니다

2024-07-13 17:48 UTC, paul2126 commented
기존 gateway가 https 라우팅을 가진 것 처럼 internal-gateway에도 동일하게 https 라우팅을 넣어야하나요?

2024-07-14 05:50 UTC, nevivurn approved these changes

2024-07-14 05:51 UTC, nevivurn commented
네 HTTPS도 추가하면 좋을 것 같습니다
어차피 내부망이라 중요도는 낮지만 해서 나쁠건 없어요

2024-07-16 17:30 UTC, nevivurn requested changes
Gateway 무시하도록 하는 설정을 제가 잘못 알려드린 것 같아요. 지금 설정은 HTTPRoute 단에서만 유효한 것 같습니다.

이대로 올려도 문제는 없는데 external-dns가 무시하지 않아서 저희 cloudflare DNS zone에 필요 없는 값들이 올라갈 것 같아요

아래 변경사항도 사실 테스트해본건 아니라서 적용해보고 external-dns가 잘 무시해주는지 확인이 필요합니다.

2024-07-18 12:01 UTC, nevivurn approved these changes

2024-07-27 08:09 UTC, merged